name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ release, main ]

permissions: {}

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Build and test
      uses: actions/setup-node@v4
      with:
        node-version: '16'
    - run: npm ci
    - run: npm run all

    - name: Check for un-staged changes
      id: diff
      run: |
        if [ "$(git diff --ignore-space-at-eol | wc -l)" -gt "0" ]; then
          echo "Detected uncommitted changes after build. See status below:"
          git diff
          exit 1
        fi
    - uses: actions/upload-artifact@v3
      if: ${{ failure() && steps.diff.conclusion == 'failure' }}
      with:
        name: dist
        path: dist/
