name: Changelog link check

on:
  pull_request_target:
    branches: [ main ]

permissions:
  pull-requests: write
  contents: read

jobs:
  check_pull_request:
    name: Check files for broken links
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          test-files
    - name: Validate files
      id: validate
      with:
        repoToken: ${{ secrets.GITHUB_TOKEN }}
        changeLogDirectory: test-files
      uses: microsoftgraph/changelog-link-check@main

